// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file MetaMessage.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _MetaMessage_H_
#define _MetaMessage_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MetaMessage_SOURCE)
#define MetaMessage_DllAPI __declspec( dllexport )
#else
#define MetaMessage_DllAPI __declspec( dllimport )
#endif // MetaMessage_SOURCE
#else
#define MetaMessage_DllAPI
#endif
#else
#define MetaMessage_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

/*!
 * @brief This class represents the structure MetaMessage defined by the user in the IDL file.
 * @ingroup METAMESSAGE
 */
class MetaMessage
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MetaMessage();
    
    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MetaMessage();
    
    /*!
     * @brief Copy constructor.
     * @param x Reference to the object MetaMessage that will be copied.
     */
    eProsima_user_DllExport MetaMessage(const MetaMessage &x);
    
    /*!
     * @brief Move constructor.
     * @param x Reference to the object MetaMessage that will be copied.
     */
    eProsima_user_DllExport MetaMessage(MetaMessage &&x);
    
    /*!
     * @brief Copy assignment.
     * @param x Reference to the object MetaMessage that will be copied.
     */
    eProsima_user_DllExport MetaMessage& operator=(const MetaMessage &x);
    
    /*!
     * @brief Move assignment.
     * @param x Reference to the object MetaMessage that will be copied.
     */
    eProsima_user_DllExport MetaMessage& operator=(MetaMessage &&x);
    
    /*!
     * @brief This function sets a value in member message_id
     * @param _message_id New value for member message_id
     */
    inline eProsima_user_DllExport void message_id(uint32_t _message_id)
    {
        m_message_id = _message_id;
    }

    /*!
     * @brief This function returns the value of member message_id
     * @return Value of member message_id
     */
    inline eProsima_user_DllExport uint32_t message_id() const
    {
        return m_message_id;
    }

    /*!
     * @brief This function returns a reference to member message_id
     * @return Reference to member message_id
     */
    inline eProsima_user_DllExport uint32_t& message_id()
    {
        return m_message_id;
    }
    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    inline eProsima_user_DllExport void data(const std::string &_data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    inline eProsima_user_DllExport void data(std::string &&_data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    inline eProsima_user_DllExport const std::string& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    inline eProsima_user_DllExport std::string& data()
    {
        return m_data;
    }
    
    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const MetaMessage& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;
    
private:
    uint32_t m_message_id;
    std::string m_data;
};

#endif // _MetaMessage_H_